# Numpy Quiz
## TechX

In [ ]:
# Task one: import dependencies and create a 3*3 zero matrix called "a" (datatype is float)



In [19]:
# sample answer:
import numpy as np
a = np.zeros((3,3),dtype=float)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# Task two: create a random matrix with shape (3,4) in the range [3,4) called "b" (datatype is float)



In [14]:
# sample answer:
b = np.random.random((3,4))+3
b

array([[3.02286403, 3.12721035, 3.32840395, 3.04132592],
       [3.80318297, 3.47017194, 3.25628236, 3.4261161 ],
       [3.61022637, 3.96804755, 3.37844623, 3.62670905]])

In [ ]:
# Task three: change the second column of "b" to [18,18,18]. Merge both "a" and "b" to a 3*7 matrix called "c"


# hint: use np.concatenate to merge matrices. Be careful for the axis

In [24]:
#sample answer
b[:,1] = 18
c = np.concatenate((a,b), axis=1)
print(b)
print(c)

[[ 3.02286403 18.          3.32840395  3.04132592]
 [ 3.80318297 18.          3.25628236  3.4261161 ]
 [ 3.61022637 18.          3.37844623  3.62670905]]
[[ 0.          0.          0.          3.02286403 18.          3.32840395
   3.04132592]
 [ 0.          0.          0.          3.80318297 18.          3.25628236
   3.4261161 ]
 [ 0.          0.          0.          3.61022637 18.          3.37844623
   3.62670905]]


In [27]:
# Bonus question: sort an array "x" using numpy (in an increasing sequence)

x = np.array([10,25,31,2,74,1,22,34,62,29,82,15,47,29])


In [29]:
#sample answer
for i in range(x.size):
    for j in range(i,x.size):
        if x[i]>x[j]:
            x[i],x[j] = x[j],x[i]
x

array([ 1,  2, 10, 15, 22, 25, 29, 29, 31, 34, 47, 62, 74, 82])