# Python and Numpy
## TechX 2021


<hr>

## Introduction

**Numpy** is a basic package for scientific computing. It is a **Python** language implementation which includes:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" alt="cce" border="0" width="25%">


* The powerful N-dimensional array structure
* Sophisticated functions
* Tools that can be integrated into C/C++ and Fortran code
* Linear algebra, Fourier transform and random number features

In addition to being used for scientific computing, NumPy also can be used as an efficient multi-dimensional container for general data. Because it can work with any type of data, NumPy can be integrated into multiple types of databases seamlessly and efficiently.

This notebook mainly introduce the basic usage of Numpy in Python and how it can help us analyze data efficiently.


<hr>

## Basic Operation of Numpy

We begin by importing numpy from the python library. Make sure that you've installed numpy or anaconda to use the package.

In [ ]:
# !pip install numpy
import numpy as np

Error: Session cannot generate requests

Different ways to create arrays in numpy:

In [ ]:
np.zeros(10, dtype="int") #The code segement create a length-10 integer array filled with zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((5,6),dtype="float") #5*6 zero matrix with float data type

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.full((3,5),3.14,dtype="float") #creating 3*5 array filled with 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence (similiar to range() function)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create a 3*3 array with random value

np.random.random((3,3))

array([[0.54698802, 0.11682423, 0.968695  ],
       [0.14728949, 0.63577226, 0.07648621],
       [0.10181587, 0.85398918, 0.04826797]])

In [ ]:
# Create a 3*3 array of normally distributed random values with mean 0 and std 1

np.random.normal(0,1,(3,3))

array([[ 0.72460171,  0.00795664,  1.46884332],
       [-0.81583816,  1.12800574,  0.19546409],
       [ 0.06243346, -0.25133146,  1.09477949]])

In [ ]:
# Create a 3*3 integer arrays in interval [0,10)

np.random.randint(0,10,(3,3))


array([[7, 7, 2],
       [2, 4, 7],
       [6, 4, 2]])

In [ ]:
# Create a 3*3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<img src="https://1.bp.blogspot.com/-xrnk-4zD2Ac/W1LCbjrSjjI/AAAAAAAAXUY/8QJ0AZBxsQ0h6BgUV4kml0NqIO_hOs2KwCLcBGAs/s1600/4212_t2-1.PNG" alt="cce" border="0">

Basic array manipulations:
* Attributes of arrays
   * Determining the size, shape, memory consumption, and data types of arrays
* Indexing of arrays
   * Getting and setting the value of individual array elements
* Slicing of arrays
   * Getting and setting smaller subarrays within a larger array
* Reshaping of arrays
   * Changing the shape of a given array
* Joining and splitting of arrays
   * Combining multiple arrays into one, and splitting one array into many

In [ ]:
np.random.seed(0) #seed for reproducibility
x1 = np.random.randint(10,size = 6)
print("x1 ndim:",x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size:",x1.size)
print("x1 dtype:", x1.dtype)
print("x1 itemsize:",x1.itemsize,"bytes")  #Size of each element
print("x1 nbytes:",x1.nbytes,"bytes") #Total size

x1 ndim: 1
x1 shape: (6,)
x1 size: 6
x1 dtype: int64
x1 itemsize: 8 bytes
x1 nbytes: 48 bytes


In [ ]:
# Array indexing

print(x1)
print(x1[0])
print(x1[-1]) #Indexing from the end of the array


[5 0 3 3 7 9]
5
9


In [ ]:
x2 = np.random.randint(20,size=(3,4))
print(x2)
print(x2[2,1])
print(x2[-2][-3])

[[19 18  4  6]
 [12  1  6  7]
 [14 17  5 13]]
17
1


In [ ]:
print(x2)
x2[0][0] = 100  #Modify value using index notations
print(x2)

[[19 18  4  6]
 [12  1  6  7]
 [14 17  5 13]]
[[100  18   4   6]
 [ 12   1   6   7]
 [ 14  17   5  13]]


In [ ]:
print(x1)
x1[0] = 3.1415926  #This will be truncated
print(x1)

[5 0 3 3 7 9]
[3 0 3 3 7 9]


In [ ]:
# Array Slicing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] #first five element

array([0, 1, 2, 3, 4])

In [ ]:
x[4:7] #sub array

array([4, 5, 6])

In [ ]:
x[::2] #slicing every 2 element

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] #same as above, starting from 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1] #reversing array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
## for multidimensional arrays
x2

array([[100,  18,   4,   6],
       [ 12,   1,   6,   7],
       [ 14,  17,   5,  13]])

In [ ]:
x2[:3,::2] #all rows, first and third column

array([[100,   4],
       [ 12,   6],
       [ 14,   5]])

In [ ]:
x2[::-1,::-1] #all reversed

array([[ 13,   5,  17,  14],
       [  7,   6,   1,  12],
       [  6,   4,  18, 100]])

In [ ]:
# reshaping arrays
x2

array([[100,  18,   4,   6],
       [ 12,   1,   6,   7],
       [ 14,  17,   5,  13]])

In [ ]:
x2.reshape(4,3)

array([[100,  18,   4],
       [  6,  12,   1],
       [  6,   7,  14],
       [ 17,   5,  13]])

In [ ]:
# Array concatenation and splitting

x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
np.concatenate((a,a))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a,a),axis=1) #concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# Splitting of arrays

x = [1,2,3,99,99,3,2,1]

x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
a = np.arange(36).reshape((6,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
upper, middle, lower = np.vsplit(a, [2,3])
print("upper:",upper)
print("middle:",middle)
print("lower:",lower)

upper: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
middle: [[12 13 14 15 16 17]]
lower: [[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
#Array arithmetic
# Very similiar to native arithmetic operators

x = np.arange(4)
print("x+5", x+5)
print("x // 2", x // 2)

x+5 [5 6 7 8]
x // 2 [0 0 1 1]


In [ ]:
print(np.add(3,2))

print(np.add(x,2)) #Addition +
print(np.subtract(x,5)) #Subtraction -
print(np.negative(x)) #Unary negation -
print(np.multiply(x,3)) #Multiplication *
print(np.divide(x,2)) #Division /
print(np.floor_divide(x,2)) #Floor division //
print(np.power(x,2)) #Exponentiation **
print(np.mod(x,2)) #Modulus/remainder **

print(np.multiply(x, x))

5
[2 3 4 5]
[-5 -4 -3 -2]
[ 0 -1 -2 -3]
[0 3 6 9]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 4 9]
[0 1 0 1]
[0 1 4 9]


In [ ]:
# summing values in array
print(np.sum(x))
print(sum(x))

6
6


In [ ]:
#The only difference between two functions is the speed
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

13 ms ± 420 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.9 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
np.min(big_array), np.max(big_array)

(4.011685566074341e-06, 0.9999993688244624)

<img src="https://3.bp.blogspot.com/-2pjqt9Ga6IM/W20-sIVK0II/AAAAAAAAXVM/BB74tRGTiwgcYTgezVLD3LKH7NFj4pjpgCLcBGAs/s1600/4214_t2-3.PNG" alt="cce" border="0">

Broadcasting:
* broadcasting is a set of rules for calculating arrays in different sizes

In [ ]:
#Here a will be automatically extend to 3*3 in order to apply the addition
a = np.ones((1,3))
b = np.ones((3,3))
a+b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" alt="broadcasting" border="0">



A general introduction about how broadcasting work

The code segment below is about applying numpy into deeplearning. We use numpy to train the mnist fashion dataset using a two layer neural network

In [ ]:
!pip install tensorflow  #for those of you who don't have tensorflow

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [ ]:
import numpy as np
import pandas as pd #used for processing data with csv files
import matplotlib.pyplot as plt #used for graphing

import tensorflow as tf #a frequently used deep learning framework
from tensorflow import keras

print(tf.__version__) #note that we are using tensorflow 2.0+

Error: Session cannot generate requests